use_frameworks!

target 'FlaatSDK_Example' do
  pod 'FlaatSDK', :path => '../'
#   pod 'TCNClient', :git => 'https://github.com/EQWorks/tcn-client-ios.git', :branch => 'master'
  pod 'TCNClient', :path => '../../forks/tcn-client-ios'

  target 'FlaatSDK_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
