use_frameworks!

target 'FlaatSDK_Example' do
  pod 'FlaatSDK', :path => '../'

  target 'FlaatSDK_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
